name: Basics

on:
  workflow_dispatch:

env:
  name: Jan
  number: ${{ 1234 }}
  
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: echo First job from ${{ env.name }}
      
      - run: gh issue create --title "basics workflow issue" --body "test creating issues from workflow"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo Second job parallel
      
  third-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - run: echo Third job sequential
