name: Basics

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo First job
  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo Second job parallel
  third-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - run: echo Third job sequential
